version: '3.8'

services:
  # FastAPI Application
  app:
    build: .
    container_name: pepti_wiki_app
    environment:
      # Database settings - will be set via .env file for external services
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_NAME: ${DATABASE_NAME}
      
      # Qdrant settings (use your cloud URL)
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      PEPTIDE_COLLECTION: ${PEPTIDE_COLLECTION:-peptides}
      
      # API Keys (set these in .env file)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SERP_API_KEY: ${SERP_API_KEY}
      
      # Search settings
      CONFIDENCE_SCORE: ${CONFIDENCE_SCORE:-70}
      
      # Server settings
      HOST: 0.0.0.0
      PORT: 8000
      DEBUG: ${DEBUG:-false}
      
      # CORS settings
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-["*"]}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
