"""Initial migration with all tables

Revision ID: 6c25423bbf6b
Revises: 
Create Date: 2025-10-24 00:27:46.191579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c25423bbf6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_external_api_usage_cost_usd'), table_name='external_api_usage')
    op.drop_index(op.f('idx_external_api_usage_created_at_cost'), table_name='external_api_usage')
    op.drop_index(op.f('idx_external_api_usage_pricing_model'), table_name='external_api_usage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_external_api_usage_pricing_model'), 'external_api_usage', ['pricing_model'], unique=False)
    op.create_index(op.f('idx_external_api_usage_created_at_cost'), 'external_api_usage', ['created_at', 'cost_usd'], unique=False)
    op.create_index(op.f('idx_external_api_usage_cost_usd'), 'external_api_usage', ['cost_usd'], unique=False)
    # ### end Alembic commands ###
